# Generated by Django 3.1.3 on 2020-12-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
