# Generated by Django 3.1.3 on 2020-12-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201227_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='type_cmplement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
