# Generated by Django 3.1.3 on 2020-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_person_type_cmplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
